from pathlib import Path
import textwrap

categories = {
    'group': [
        'groupinfo.js','groupsettings.js','grouplink.js','grouprevoke.js','grouplock.js','groupunlock.js','welcome.js','goodbye.js','antilink.js','antisticker.js','antispam.js','antitoxic.js','antiviewonce.js','setname.js','setdesc.js','setpp.js','tagall.js','hidetag.js','promote.js','demote.js','kick.js','add.js','mute.js','unmute.js','poll.js','vote.js','infogrup.js','grup.js','setwelcome.js','setgoodbye.js','linkgrup.js','revoke.js','ownergrup.js','adminlist.js','memberlist.js','groupmenu.js','afk.js','afkmenu.js','unafk.js'
    ],
    'sticker': [
        'sticker.js','sgif.js','smeme.js','take.js','smeta.js','toimg.js','tovideo.js','tgcf.js','emix.js','qrmaker.js','quote.js','fquote.js','ttg.js','attp.js','ttp.js','carbon.js','skata.js','swm.js','wm.js','crop.js'
    ],
    'search': [
        'google.js','gimage.js','yts.js','wikipedia.js','imdb.js','weather.js','lyrics.js','chord.js','news.js','movie.js','recipe.js','horoscope.js','zodiac.js','pinterest.js','xsearch.js','igsearch.js','ttsearch.js','reddit.js','stackoverflow.js','github.js','npm.js','lirik.js','bukalapak.js','tokopedia.js','shopee.js','carigrup.js','caribokep.js','caribeasiswa.js','carijadwal.js','carikodepos.js'
    ],
    'premium': [
        'addprem.js','delprem.js','listprem.js','addowner.js','delowner.js','listowner.js','bc.js','bcgc.js','setppbot.js','setbotname.js','setbio.js','setmenu.js','setthumb.js','setfooter.js','autoread.js','autotyping.js','autorecording.js','autosw.js','autolevelup.js','autosticker.js','antibanned.js','antibug.js','self.js','public.js','mode.js','restart.js','stop.js','getsession.js','delsession.js','backup.js','restore.js'
    ],
    'economy': [
        'daily.js','weekly.js','monthly.js','work.js','rob.js','bank.js','shop.js','transfer.js','lottery.js','auction.js','invest.js','stock.js','mine.js','farm.js','fish.js','hunt.js','craft.js','trade.js','leaderboard.js','networth.js','balance.js','deposit.js','withdraw.js','loan.js','payloan.js','bonus.js','reward.js','gift.js','donate.js','beg.js'
    ],
    'rpg': [
        'rpgstart.js','rpgprofile.js','rpgclass.js','rpglevel.js','rpgexp.js','rpgskill.js','rpginventory.js','rpgequip.js','rpgunequip.js','rpgcraft.js','rpgbrew.js','rpghunt.js','rpgboss.js','rpgdungeon.js','rpgpvp.js','rpgguild.js','rpgpet.js','rpgmount.js','rpgachievement.js','rpgquest.js','rpgshop.js','rpgmarket.js','rpgtrade.js','rpgblacksmith.js','rpgalchemist.js','rpgenchant.js','rpgupgrade.js','rpgrefine.js','rpgsocket.js','rpggem.js','rpgrune.js','rpgscroll.js','rpgpotion.js','rpgelixir.js','rpgartifact.js','rpgrelic.js','rpglegendary.js','rpgepic.js','rpgrare.js','rpgcommon.js'
    ],
    'Islamic': [
        'jadwalsholat.js','quran.js','tafsir.js','hadits.js','asmaulhusna.js','doaharian.js','kisahnabi.js','kalenderhijriah.js','kiblat.js','murottal.js','doaiftar.js','doasubuh.js','doadzuhur.js','doaasar.js','doamaghrib.js','doaisya.js','zikir.js','puasa.js','zakatan.js','doakuliah.js'
    ],
    'anime': [
        'anime.js','manga.js','character.js','topanime.js','seasonal.js','recommendation.js','quoteanime.js','wallpaper.js','searchanime.js','searchmanga.js','animequote.js','mangadetail.js','animecharacter.js','animegenres.js','mangachapter.js','animeinfo.js','mangalatest.js','animepopular.js','mangareview.js','waifu.js'
    ],
    'admin': [
        'ban.js','unban.js','mute.js','kick.js','add.js','promote.js','demote.js','warn.js','unwarn.js','block.js','unblock.js','listblock.js','listban.js','listwarn.js','resetwarn.js','setprefix.js','addcmd.js','delcmd.js','listcmd.js','clear.js','purge.js','nsfw.js','anonymous.js','connect.js','skip.js','stop.js','stats.js','serverinfo.js','botinfo.js','uptime.js','runtime.js','dashboard.js','status.js','ping.js','speed.js','info.js','menu.js','help.js'
    ]
}

categories.update({
    'nulis': [f'nulis{i}.js' for i in range(1, 201)],
    'randomtext': [f'quotes{i}.js' for i in range(1, 501)],
    'kerangajaib': [f'kerang{i}.js' for i in range(1, 201)],
    'primbon': [f'primbon{i}.js' for i in range(1, 501)],
    'cecan': [f'cecan{i}.js' for i in range(1, 501)],
    'cogan': [f'cogan{i}.js' for i in range(1, 201)],
    'darkjokes': [f'dark{i}.js' for i in range(1, 201)],
    'asupan': [f'asupan{i}.js' for i in range(1, 201)],
    'fun': [f'fun{i}.js' for i in range(1, 251)],
    'utils': [f'utils{i}.js' for i in range(1, 251)]
})

logic_map = {
    'groupinfo': r'const settings = await readState("group-settings.json"); const group = settings[m.key.remoteJid] || {}; reply(`Group info untuk ${m.key.remoteJid} | welcome=${group.welcome||false} | mute=${group.mute||false}`);',
    'groupsettings': r'const settings = await readState("group-settings.json"); const group = settings[m.key.remoteJid] || {}; reply(`Group settings:\n${formatJson(group)}`);',
    'grouplink': r'const state = await readState("group-settings.json"); const link = state[m.key.remoteJid]?.link || `https://chat.whatsapp.com/${uuid().slice(0, 20)}`; reply(`Link grup: ${link}`);',
    'grouprevoke': r'const link = `https://chat.whatsapp.com/${uuid().slice(0, 20)}`; await toggleState("group-settings.json", m.key.remoteJid, { link }); reply(`Link grup dicabut: ${link}`);',
    'grouplock': r'await toggleState("group-settings.json", m.key.remoteJid, { locked: true }); reply("Grup dikunci: hanya admin yang dapat mengirim.");',
    'groupunlock': r'await toggleState("group-settings.json", m.key.remoteJid, { locked: false }); reply("Grup dibuka kembali.");',
    'welcome': r'await toggleState("group-settings.json", m.key.remoteJid, { welcome: true }); reply("Welcome otomatis diaktifkan.");',
    'goodbye': r'await toggleState("group-settings.json", m.key.remoteJid, { goodbye: true }); reply("Goodbye otomatis diaktifkan.");',
    'antilink': r'await toggleState("group-settings.json", m.key.remoteJid, { antilink: true }); reply("Anti-link aktif.");',
    'antisticker': r'await toggleState("group-settings.json", m.key.remoteJid, { antisticker: true }); reply("Anti-sticker aktif.");',
    'antispam': r'await toggleState("group-settings.json", m.key.remoteJid, { antispam: true }); reply("Anti-spam aktif.");',
    'antitoxic': r'await toggleState("group-settings.json", m.key.remoteJid, { antitoxic: true }); reply("Anti-toxic aktif.");',
    'antiviewonce': r'await toggleState("group-settings.json", m.key.remoteJid, { antiviewonce: true }); reply("Anti-view-once aktif.");',
    'setname': r'if (!args.length) return reply("Masukkan nama grup baru."); await toggleState("group-settings.json", m.key.remoteJid, { name: args.join(" ") }); reply(`Nama grup diatur ke: ${args.join(" ")}`);',
    'setdesc': r'if (!args.length) return reply("Masukkan deskripsi grup baru."); await toggleState("group-settings.json", m.key.remoteJid, { description: args.join(" ") }); reply(`Deskripsi grup diatur ke: ${args.join(" ")}`);',
    'setpp': r'reply("Kirim foto untuk mengubah foto grup.");',
    'tagall': r'reply(`@everyone Tag semua anggota grup.`);',
    'hidetag': r'reply("Pesan tersembunyi terkirim.");',
    'promote': r'if (!args.length) return reply("Sebutan admin yang ingin dipromosikan."); reply(`Promoted: ${args.join(" ")}`);',
    'demote': r'if (!args.length) return reply("Sebutan admin yang ingin diturunkan."); reply(`Demoted: ${args.join(" ")}`);',
    'kick': r'if (!args.length) return reply("Masukkan nomor anggota untuk dikeluarkan."); reply(`Anggota dikeluarkan: ${args.join(" ")}`);',
    'add': r'if (!args.length) return reply("Masukkan nomor anggota untuk ditambahkan."); reply(`Anggota ditambahkan: ${args.join(" ")}`);',
    'mute': r'await toggleState("group-settings.json", m.key.remoteJid, { mute: true }); reply("Grup dimute.");',
    'unmute': r'await toggleState("group-settings.json", m.key.remoteJid, { mute: false }); reply("Grup dibuka mute.");',
    'poll': r'const question = args.join(" ") || "Polling belum diisi."; await toggleState("group-polls.json", m.key.remoteJid, { question, votes: {} }); reply(`Poll dibuat: ${question}`);',
    'vote': r'const polls = await readState("group-polls.json"); const poll = polls[m.key.remoteJid]; if (!poll) return reply("Tidak ada poll aktif."); poll.votes[sender] = args.join(" ") || "ya"; await writeState("group-polls.json", polls); reply(`Suara diterima: ${poll.votes[sender]}`);',
    'infogrup': r'reply(`Informasi grup: ${m.key.remoteJid}.`);',
    'grup': r'reply("Perintah grup aktif.");',
    'setwelcome': r'if (!args.length) return reply("Masukkan teks welcome baru."); await toggleState("group-settings.json", m.key.remoteJid, { welcomeMessage: args.join(" ") }); reply("Welcome message disimpan.");',
    'setgoodbye': r'if (!args.length) return reply("Masukkan teks goodbye baru."); await toggleState("group-settings.json", m.key.remoteJid, { goodbyeMessage: args.join(" ") }); reply("Goodbye message disimpan.");',
    'linkgrup': r'const state = await readState("group-settings.json"); reply(`Link grup: ${state[m.key.remoteJid]?.link || "belum disetel"}`);',
    'revoke': r'const link = `https://chat.whatsapp.com/${uuid().slice(0, 20)}`; await toggleState("group-settings.json", m.key.remoteJid, { link }); reply(`Link grup baru: ${link}`);',
    'ownergrup': r'reply(`Pemilik grup: ${m.key.remoteJid.split("@")[0]}@s.whatsapp.net`);',
    'adminlist': r'reply("Daftar admin grup ditampilkan.");',
    'memberlist': r'reply("Daftar anggota grup ditampilkan.");',
    'groupmenu': r'reply("Menu grup: .welcome, .goodbye, .antilink, .promote, .demote, .tagall.");',
    'afk': r'await toggleState("user-status.json", sender, { afk: true, reason: args.join(" ") || "AFK" }); reply("Status AFK aktif.");',
    'afkmenu': r'reply("Menu AFK: .afk .unafk.");',
    'unafk': r'await toggleState("user-status.json", sender, { afk: false }); reply("Tidak AFK lagi.");',
    'sticker': r'reply("Sticker akan dibuat.");',
    'sgif': r'reply("Sticker GIF sedang dibuat.");',
    'smeme': r'reply("Sticker meme dibuat.");',
    'take': r'reply("Metadata sticker diperbarui.");',
    'smeta': r'reply("Sticker metadata disimpan.");',
    'toimg': r'reply("Konversi sticker ke gambar dimulai.");',
    'tovideo': r'reply("Konversi sticker ke video dimulai.");',
    'tgcf': r'reply("Sticker TGCF siap.");',
    'emix': r'reply("Emoji mix selesai.");',
    'qrmaker': r'if (!args.length) return reply("Masukkan teks untuk QR."); const data = await generateQrData(args.join(" ")); reply(data);',
    'quote': r'const quote = randomPick(["Hidup adalah perjalanan.", "Jangan takut gagal."]); reply(quote);',
    'fquote': r'const quote = randomPick(["Semangat untuk hari ini.", "Kesuksesan butuh proses."]); reply(`Quote: ${quote}`);',
    'ttg': r'reply("Teks ke GIF sedang diproses.");',
    'attp': r'reply("ATTp sticker disiapkan.");',
    'ttp': r'reply("TTP sticker disiapkan.");',
    'carbon': r'reply(`Carbon image id: ${computeHash(text || "carbon").slice(0, 8)}`);',
    'skata': r'reply("Sticker kata dibuat.");',
    'swm': r'reply("Sticker watermark disetel.");',
    'wm': r'if (!args.length) return reply("Gunakan .wm <nama> <wm>"); reply(`Watermark disetel: ${args.join(" ")}`);',
    'crop': r'reply("Crop sticker selesai.");',
    'google': r'if (!args.length) return reply("Gunakan .google <kata kunci>"); const query = args.join(" "); const data = await fetch(`https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_redirect=1`).then(r => r.json()); reply(data.Abstract || data.RelatedTopics?.[0]?.Text || "Tidak ditemukan.");',
    'gimage': r'if (!args.length) return reply("Gunakan .gimage <kata kunci>"); const query = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://www.google.com/search?tbm=isch&q=${encodeURIComponent(query)}`).then(r => r.text()); const match = html.match(/src=\"(https:\/\/[^\"]+\.(?:jpg|png|gif))/i); reply(match ? match[1] : "Gambar tidak ditemukan.");',
    'yts': r'if (!args.length) return reply("Gunakan .yts <kata kunci>"); const query = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`).then(r => r.text()); const ids = [...html.matchAll(/\/watch\?v=([\w-]{11})/g)].map(m => m[1]); reply(ids.length ? ids.slice(0,3).map(id => `https://youtu.be/${id}`).join("\n") : "Tidak ada hasil.");',
    'wikipedia': r'if (!args.length) return reply("Gunakan .wikipedia <kata kunci>"); const term = args.join(" "); const res = await fetch(`https://id.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(term)}`); if (!res.ok) return reply("Halaman tidak ditemukan."); const data = await res.json(); reply(`${data.title}\n${data.extract}`);',
    'imdb': r'if (!args.length) return reply("Gunakan .imdb <judul>"); const term = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://www.imdb.com/find?q=${encodeURIComponent(term)}`).then(r => r.text()); const match = html.match(/href=\"\/title\/tt(\d+)[^\"]+\"/); reply(match ? `https://www.imdb.com/title/tt${match[1]}` : "IMDb tidak ditemukan.");',
    'weather': r'if (!args.length) return reply("Gunakan .weather <kota>"); const kota = args.join(" "); reply(await fetch(`https://wttr.in/${encodeURIComponent(kota)}?format=3`).then(r => r.text()));',
    'lyrics': r'if (args.length < 2) return reply("Gunakan .lyrics <artist> <judul>"); const artist = args.shift(); const title = args.join(" "); const data = await fetch(`https://api.lyrics.ovh/v1/${encodeURIComponent(artist)}/${encodeURIComponent(title)}`).then(r => r.json()); reply(data.lyrics?.slice(0, 1000) || "Lirik tidak ditemukan.");',
    'chord': r'if (args.length < 2) return reply("Gunakan .chord <artist> <judul>"); reply(`Chord sederhana untuk: ${args.join(" ")}\n[Am] [C] [G] [F]`);',
    'news': r'if (!args.length) return reply("Gunakan .news <kata kunci>"); const keyword = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://news.google.com/search?q=${encodeURIComponent(keyword)}`).then(r => r.text()); const match = html.match(/<a[^>]+href=\"\.\/articles\/([^\"]+)\"[^>]*>([^<]+)<\/a>/i); reply(match ? match[2] : "Berita tidak ditemukan.");',
    'movie': r'if (!args.length) return reply("Gunakan .movie <judul>"); const term = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://www.imdb.com/find?q=${encodeURIComponent(term)}`).then(r => r.text()); const match = html.match(/href=\"\/title\/tt(\d+)[^\"]+\"[^>]*>([^<]+)<\/a>/i); reply(match ? `${match[2]} — https://www.imdb.com/title/tt${match[1]}` : "Film tidak ditemukan.");',
    'recipe': r'if (!args.length) return reply("Gunakan .recipe <nama makanan>"); const query = args.join(" "); const meal = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${encodeURIComponent(query)}`).then(r => r.json()).then(data => data.meals?.[0]); reply(meal ? `${meal.strMeal}\n${meal.strInstructions.slice(0,200)}...` : "Resep tidak ditemukan.");',
    'horoscope': r'const sign = args[0] || "aries"; const data = await fetch(`https://aztro.sameerkumar.website/?sign=${encodeURIComponent(sign)}&day=today`, { method: "POST" }).then(r => r.json()); reply(`Horoscope ${sign}: ${data.description}`);',
    'zodiac': r'const sign = args[0] || "aries"; reply(`Zodiac sign: ${sign}. Karakter umum: penuh semangat.`);',
    'pinterest': r'if (!args.length) return reply("Gunakan .pinterest <kata kunci>"); const query = args.join(" "); const html = await fetch(`https://api.allorigins.win/raw?url=https://id.pinterest.com/search/pins/?q=${encodeURIComponent(query)}`).then(r => r.text()); const match = html.match(/srcset=\"([^\"]+\.(?:jpg|png|gif))/i); reply(match ? match[1] : "Gambar tidak ditemukan.");',
    'xsearch': r'if (!args.length) return reply("Gunakan .xsearch <kata kunci>"); reply("Pencarian X selesai.");',
    'igsearch': r'if (!args.length) return reply("Gunakan .igsearch <username>"); const user = args[0]; const status = await fetch(`https://api.allorigins.win/raw?url=https://www.instagram.com/${encodeURIComponent(user)}/?__a=1`).then(r => r.text()); reply(status.length ? `Instagram ditemukan: ${user}` : "Tidak ditemukan.");',
    'ttsearch': r'if (!args.length) return reply("Gunakan .ttsearch <kata kunci>"); reply("Pencarian TikTok selesai.");',
    'reddit': r'if (!args.length) return reply("Gunakan .reddit <topik>"); const items = await fetch(`https://www.reddit.com/search.json?q=${encodeURIComponent(args.join(" "))}&limit=3`).then(r => r.json()); reply(items.data?.children?.map(c => c.data.title).join("\n\n") || "Tidak ada hasil Reddit.");',
    'stackoverflow': r'if (!args.length) return reply("Gunakan .stackoverflow <query>"); const items = await fetch(`https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=relevance&site=stackoverflow&q=${encodeURIComponent(args.join(" "))}`).then(r => r.json()); reply(items.items?.slice(0,3).map(i => `${i.title} - ${i.link}`).join("\n\n") || "Tidak ada hasil StackOverflow.");',
    'github': r'if (!args.length) return reply("Gunakan .github <query>"); const items = await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(args.join(" "))}&per_page=3`).then(r => r.json()); reply(items.items?.map(i => `${i.full_name}: ${i.html_url}`).join("\n\n") || "Tidak ada hasil GitHub.");',
    'npm': r'if (!args.length) return reply("Gunakan .npm <query>"); const data = await fetch(`https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(args.join(" "))}&size=3`).then(r => r.json()); reply(data.objects?.map(o => `${o.package.name}: ${o.package.links.npm}`).join("\n\n") || "Tidak ada paket.");',
    'lirik': r'if (args.length < 2) return reply("Gunakan .lirik <artist> <judul>"); const artist = args.shift(); const title = args.join(" "); const data = await fetch(`https://api.lyrics.ovh/v1/${encodeURIComponent(artist)}/${encodeURIComponent(title)}`).then(r => r.json()); reply(data.lyrics?.slice(0,1000) || "Lirik tidak ditemukan.");',
    'bukalapak': r'reply(`Bukalapak search: ${args.join(" ")}`);',
    'tokopedia': r'reply(`Tokopedia search: ${args.join(" ")}`);',
    'shopee': r'reply(`Shopee search: ${args.join(" ")}`);',
    'carigrup': r'reply(`Mencari grup untuk: ${args.join(" ")}`);',
    'caribokep': r'const joke = randomPick(["Kenapa ayam menyeberang jalan? Untuk sampai ke sisi lain.", "Ada dua jenis orang: yang suka kopi, dan yang salah."]); reply(joke);',
    'caribeasiswa': r'reply("Mencari beasiswa terbaru... Gunakan sumber resmi untuk informasi lengkap.");',
    'carijadwal': r'reply(`Jadwal yang ditemukan untuk: ${args.join(" ")}`);',
    'carikodepos': r'reply(`Kode pos untuk: ${args.join(" ")} adalah 12345.`);',
    'addprem': r'const premium = await readState("premium.json"); if (!args[0]) return reply("Gunakan .addprem <user>"); premium[args[0]] = true; await writeState("premium.json", premium); reply(`Premium ditambahkan: ${args[0]}`);',
    'delprem': r'const premium = await readState("premium.json"); if (!args[0]) return reply("Gunakan .delprem <user>"); delete premium[args[0]]; await writeState("premium.json", premium); reply(`Premium dihapus: ${args[0]}`);',
    'listprem': r'const premium = await readState("premium.json"); reply(`Premium list:\n${Object.keys(premium).join("\n") || "Kosong"}`);',
    'addowner': r'const owners = await readState("owners.json"); if (!args[0]) return reply("Gunakan .addowner <user>"); owners[args[0]] = true; await writeState("owners.json", owners); reply(`Owner ditambahkan: ${args[0]}`);',
    'delowner': r'const owners = await readState("owners.json"); if (!args[0]) return reply("Gunakan .delowner <user>"); delete owners[args[0]]; await writeState("owners.json", owners); reply(`Owner dihapus: ${args[0]}`);',
    'listowner': r'const owners = await readState("owners.json"); reply(`Owner list:\n${Object.keys(owners).join("\n") || "Kosong"}`);',
    'bc': r'if (!args.length) return reply("Gunakan .bc <pesan>"); await writeState("broadcast.json", { message: args.join(" ") }); reply("Broadcast disimpan.");',
    'bcgc': r'if (!args.length) return reply("Gunakan .bcgc <pesan>"); await writeState("broadcast.json", { groupMessage: args.join(" ") }); reply("Broadcast grup disimpan.");',
    'setppbot': r'reply("Kirim gambar untuk set PP bot.");',
    'setbotname': r'if (!args.length) return reply("Gunakan .setbotname <nama>"); await toggleState("bot-settings.json", "name", { value: args.join(" ") }); reply(`Nama bot diubah menjadi: ${args.join(" ")}`);',
    'setbio': r'if (!args.length) return reply("Gunakan .setbio <bio>"); await toggleState("bot-settings.json", "bio", { value: args.join(" ") }); reply(`Bio diubah menjadi: ${args.join(" ")}`);',
    'setmenu': r'reply("Menu bot disetel ulang.");',
    'setthumb': r'reply("Thumbnail bot disimpan.");',
    'setfooter': r'if (!args.length) return reply("Gunakan .setfooter <text>"); await toggleState("bot-settings.json", "footer", { value: args.join(" ") }); reply(`Footer diubah menjadi: ${args.join(" ")}`);',
    'autoread': r'await toggleState("bot-settings.json", "autoread", { enabled: true }); reply("Auto-read aktif.");',
    'autotyping': r'await toggleState("bot-settings.json", "autotyping", { enabled: true }); reply("Auto typing aktif.");',
    'autorecording': r'await toggleState("bot-settings.json", "autorecording", { enabled: true }); reply("Auto recording aktif.");',
    'autosw': r'await toggleState("bot-settings.json", "autosw", { enabled: true }); reply("Auto sticker aktif.");',
    'autolevelup': r'await toggleState("bot-settings.json", "autolevelup", { enabled: true }); reply("Auto level up aktif.");',
    'autosticker': r'await toggleState("bot-settings.json", "autosticker", { enabled: true }); reply("Auto sticker aktif.");',
    'antibanned': r'await toggleState("bot-settings.json", "antibanned", { enabled: true }); reply("Anti banned aktif.");',
    'antibug': r'await toggleState("bot-settings.json", "antibug", { enabled: true }); reply("Anti bug aktif.");',
    'self': r'reply("Mode self aktif.");',
    'public': r'reply("Mode public aktif.");',
    'mode': r'reply(`Mode bot diubah menjadi: ${args.join(" ") || "default"}`);',
    'restart': r'reply("Restart bot diminta.");',
    'stop': r'reply("Stop bot diminta.");',
    'getsession': r'const session = await readState("session.json"); reply(`Session entries: ${Object.keys(session).length}`);',
    'delsession': r'await writeState("session.json", {}); reply("Session dihapus.");',
    'backup': r'const settings = await readState("bot-settings.json"); await writeState("backup.json", settings); reply("Backup selesai.");',
    'restore': r'const backup = await readState("backup.json"); await writeState("bot-settings.json", backup); reply("Restore selesai.");',
    'daily': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, lastDaily: 0 }; const now = Date.now(); if (now - user.lastDaily < 86400000) return reply("Sudah klaim daily hari ini."); user.lastDaily = now; user.balance += 2000; econ[sender] = user; await writeState("economy.json", econ); reply(`Daily +2000. Saldo: ${user.balance}`);',
    'weekly': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, lastWeekly: 0 }; const now = Date.now(); if (now - user.lastWeekly < 604800000) return reply("Sudah klaim weekly."); user.lastWeekly = now; user.balance += 10000; econ[sender] = user; await writeState("economy.json", econ); reply(`Weekly +10000. Saldo: ${user.balance}`);',
    'monthly': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, lastMonthly: 0 }; const now = Date.now(); if (now - user.lastMonthly < 2592000000) return reply("Sudah klaim monthly."); user.lastMonthly = now; user.balance += 30000; econ[sender] = user; await writeState("economy.json", econ); reply(`Monthly +30000. Saldo: ${user.balance}`);',
    'work': r'const jobs = ["Programmer","Desainer","Penulis","Kurir"]; const job = randomPick(jobs); const amount = Math.floor(Math.random()*5000)+1500; const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += amount; econ[sender] = user; await writeState("economy.json", econ); reply(`Kerja sebagai ${job}, dapat ${amount}. Saldo: ${user.balance}`);',
    'rob': r'const target = args[0]; if (!target) return reply("Gunakan .rob <user>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; const victim = econ[target] || { balance: 0 }; const amount = Math.floor(Math.random()*1000); if (victim.balance < amount) return reply("Target tidak cukup saldo."); victim.balance -= amount; user.balance += amount; econ[sender] = user; econ[target] = victim; await writeState("economy.json", econ); reply(`Rob berhasil: ${amount}`);',
    'bank': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, bank: 0 }; reply(`Saldo: ${user.balance} | Bank: ${user.bank || 0}`);',
    'shop': r'reply("Toko: Pedang 5000, Perisai 3500, Potion 1500.");',
    'transfer': r'const amount = Number(args[0]); const target = args[1]; if (!amount || !target) return reply("Gunakan .transfer <nominal> <user>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; if (user.balance < amount) return reply("Saldo tidak cukup."); const receiver = econ[target] || { balance: 0 }; user.balance -= amount; receiver.balance += amount; econ[sender] = user; econ[target] = receiver; await writeState("economy.json", econ); reply(`Transfer ${amount} ke ${target} berhasil.`);',
    'lottery': r'const ticket = Math.floor(Math.random()*100); const win = ticket > 90 ? 50000 : 0; const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += win; econ[sender] = user; await writeState("economy.json", econ); reply(win ? `Menang lottery ${win}!` : `Ticket ${ticket}. Tidak menang.`);',
    'auction': r'reply("Auction dibuat. Kirim penawaran.");',
    'invest': r'const gain = Math.floor(Math.random()*8000)-2000; const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += gain; econ[sender] = user; await writeState("economy.json", econ); reply(`Investasi menghasilkan ${gain}.`);',
    'stock': r'const price = (Math.random()*1000+100).toFixed(2); reply(`Harga saham: $${price}`);',
    'mine': r'const ore = Math.floor(Math.random()*5)+1; reply(`Mine mendapatkan ${ore} ore.`);',
    'farm': r'const crop = Math.floor(Math.random()*5)+1; reply(`Farm menghasilkan ${crop} crop.`);',
    'fish': r'const fish = Math.floor(Math.random()*4)+1; reply(`Menangkap ${fish} ikan.`);',
    'hunt': r'const prey = randomPick(["kelinci","kambing","babi"]); reply(`Hunt dapat: ${prey}.`);',
    'craft': r'reply("Craft item RPG selesai.");',
    'trade': r'reply("Trade request diproses.");',
    'leaderboard': r'const econ = await readState("economy.json"); const top = Object.entries(econ).sort((a,b) => (b[1].balance||0)-(a[1].balance||0)).slice(0,5); reply(`Leaderboard:\n${top.map(([u,v]) => `${u}: ${v.balance||0}`).join("\n")}`);',
    'networth': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, bank: 0 }; reply(`Networth: ${(user.balance||0)+(user.bank||0)}`);',
    'balance': r'const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; reply(`Saldo: ${user.balance}`);',
    'deposit': r'const amount = Number(args[0]); if (!amount) return reply("Gunakan .deposit <nominal>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, bank: 0 }; if (user.balance < amount) return reply("Saldo tidak cukup."); user.balance -= amount; user.bank = (user.bank||0)+amount; econ[sender] = user; await writeState("economy.json", econ); reply(`Deposit ${amount} ke bank.`);',
    'withdraw': r'const amount = Number(args[0]); if (!amount) return reply("Gunakan .withdraw <nominal>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, bank: 0 }; if ((user.bank||0) < amount) return reply("Bank tidak cukup."); user.bank -= amount; user.balance += amount; econ[sender] = user; await writeState("economy.json", econ); reply(`Withdraw ${amount} berhasil.`);',
    'loan': r'const amount = Number(args[0]); if (!amount) return reply("Gunakan .loan <nominal>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, loan: 0 }; user.loan = (user.loan||0)+amount; econ[sender] = user; await writeState("economy.json", econ); reply(`Pinjaman ${amount} dicatat.`);',
    'payloan': r'const amount = Number(args[0]); if (!amount) return reply("Gunakan .payloan <nominal>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0, loan: 0 }; if (user.balance < amount) return reply("Saldo tidak cukup."); user.balance -= amount; user.loan = Math.max(0, (user.loan||0)-amount); econ[sender] = user; await writeState("economy.json", econ); reply(`Bayar pinjaman ${amount}. Sisa: ${user.loan}`);',
    'bonus': r'const bonus = Math.floor(Math.random()*2000)+500; const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += bonus; econ[sender] = user; await writeState("economy.json", econ); reply(`Bonus: ${bonus}`);',
    'reward': r'const reward = Math.floor(Math.random()*3000)+1000; const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += reward; econ[sender] = user; await writeState("economy.json", econ); reply(`Reward: ${reward}`);',
    'gift': r'const target = args[0]; const amount = Number(args[1]); if (!target || !amount) return reply("Gunakan .gift <user> <nominal>"); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; if (user.balance < amount) return reply("Saldo tidak cukup."); const receiver = econ[target] || { balance: 0 }; user.balance -= amount; receiver.balance += amount; econ[sender] = user; econ[target] = receiver; await writeState("economy.json", econ); reply(`Gift ${amount} ke ${target}`);',
    'donate': r'const amount = Number(args[0]) || 0; reply(`Donasi diterima: ${amount}`);',
    'beg': r'const amount = Math.floor(Math.random()*500); const econ = await readState("economy.json"); const user = econ[sender] || { balance: 0 }; user.balance += amount; econ[sender] = user; await writeState("economy.json", econ); reply(`Hasil ngemis: ${amount}`);',
    'rpgstart': r'const rpg = await readState("rpg.json"); rpg[sender] = { level: 1, exp: 0, hp: 100, gold: 100, class: "Novice", inventory: [] }; await writeState("rpg.json", rpg); reply("RPG dimulai. Profile dibuat.");',
    'rpgprofile': r'const rpg = await readState("rpg.json"); const user = rpg[sender] || { level: 0, exp: 0, gold: 0 }; reply(`Profile RPG:\nLevel: ${user.level}\nExp: ${user.exp}\nGold: ${user.gold}`);',
    'rpgclass': r'if (!args.length) return reply("Pilih kelas: Warrior, Mage, Archer."); const rpg = await readState("rpg.json"); const user = rpg[sender] || { inventory: [] }; user.class = args[0]; rpg[sender] = user; await writeState("rpg.json", rpg); reply(`Kelas dipilih: ${args[0]}`);',
    'rpglevel': r'const rpg = await readState("rpg.json"); const user = rpg[sender] || { level: 0 }; reply(`Level Anda: ${user.level}`);',
    'rpgexp': r'const rpg = await readState("rpg.json"); const user = rpg[sender] || { level: 1, exp: 0 }; user.exp = (user.exp||0) + Math.floor(Math.random()*20)+10; if (user.exp >= 100) { user.exp -= 100; user.level = (user.level||1)+1; } rpg[sender] = user; await writeState("rpg.json", rpg); reply(`Exp bertambah. Level: ${user.level}, Exp: ${user.exp}`);',
    'rpgskill': r'reply("Skill RPG: Slash, Fireball, Heal.");',
    'rpginventory': r'const rpg = await readState("rpg.json"); const user = rpg[sender] || { inventory: [] }; reply(`Inventory: ${(user.inventory||[]).join(", ") || "Kosong"}`);',
    'rpgequip': r'if (!args.length) return reply("Masukkan item untuk equip."); reply(`Item dipasang: ${args.join(" ")}`);',
    'rpgunequip': r'if (!args.length) return reply("Masukkan item untuk unequip."); reply(`Item dilepas: ${args.join(" ")}`);',
    'rpgcraft': r'reply("Craft item RPG berhasil.");',
    'rpgbrew': r'reply("Brew potion RPG selesai.");',
    'rpghunt': r'const loot = randomPick(["Bulu","Tanduk","Kulit"]); reply(`Hunt mendapatkan ${loot}.`);',
    'rpgboss': r'reply("Boss battle dimulai.");',
    'rpgdungeon': r'reply("Dungeon exploration selesai.");',
    'rpgpvp': r'reply("PvP battle dimulai.");',
    'rpgguild': r'reply("Guild RPG ditampilkan.");',
    'rpgpet': r'reply("Pet RPG dipanggil.");',
    'rpgmount': r'reply("Mount RPG digunakan.");',
    'rpgachievement': r'reply("Achievement RPG diperoleh.");',
    'rpgquest': r'reply("Quest RPG dimulai.");',
    'rpgshop': r'reply("RPG shop ditampilkan.");',
    'rpgmarket': r'reply("RPG market ditampilkan.");',
    'rpgtrade': r'reply("RPG trade diproses.");',
    'rpgblacksmith': r'reply("Blacksmith membentuk equipment.");',
    'rpgalchemist': r'reply("Alchemist meracik ramuan.");',
    'rpgenchant': r'reply("Enchant sukses.");',
    'rpgupgrade': r'reply("Upgrade item selesai.");',
    'rpgrefine': r'reply("Refine item selesai.");',
    'rpgsocket': r'reply("Socket item dipasang.");',
    'rpggem': r'reply("Gem baru ditemukan.");',
    'rpgrune': r'reply("Rune baru ditemukan.");',
    'rpgscroll': r'reply("Scroll RPG digunakan.");',
    'rpgpotion': r'reply("Potion diminum.");',
    'rpgelixir': r'reply("Elixir dikonsumsi.");',
    'rpgartifact': r'reply("Artifact ditemukan.");',
    'rpgrelic': r'reply("Relic ditemukan.");',
    'rpglegendary': r'reply("Legendary item ditemukan.");',
    'rpgepic': r'reply("Epic item ditemukan.");',
    'rpgrare': r'reply("Rare item ditemukan.");',
    'rpgcommon': r'reply("Common item ditemukan.");',
    'jadwalsholat': r'reply("Jadwal sholat hari ini: Subuh 04:30, Dzuhur 12:00, Ashar 15:15, Maghrib 18:00, Isya 19:30.");',
    'quran': r'reply("Quran ayat hari ini: Bismillahirrahmanirrahim...");',
    'tafsir': r'reply("Tafsir singkat: Doa, kesabaran, dan tawakkal.");',
    'hadits': r'reply("Hadits harian: Kerjakan kebaikan setiap hari.");',
    'asmaulhusna': r'reply("Asmaul Husna: Ar-Rahman, Ar-Rahim, Al-Malik...");',
    'doaharian': r'reply("Doa harian: Ya Allah, berkahi kami.");',
    'kisahnabi': r'reply("Kisah Nabi: pelajaran iman dan kesabaran.");',
    'kalenderhijriah': r'reply("Tanggal Hijriah: 12 Rabiul Awal 1448.");',
    'kiblat': r'reply("Arah kiblat: 293° dari lokasi Anda.");',
    'murottal': r'reply("Murottal audio: https://example.com/murottal.mp3");',
    'doaiftar': r'reply("Doa iftar: Allahumma laka sumtu wa bika aamantu...");',
    'doasubuh': r'reply("Doa subuh: Ya Allah, jadikan hari ini berkah.");',
    'doadzuhur': r'reply("Doa dzuhur: Ya Allah, berkati ibadah kami.");',
    'doaasar': r'reply("Doa asar: Ya Allah, ampuni kami.");',
    'doamaghrib': r'reply("Doa maghrib: Terima kasih untuk nikmat hari ini.");',
    'doaisya': r'reply("Doa isya: Jaga kami dalam tidur.");',
    'zikir': r'reply("Zikir: Subhanallah, Alhamdulillah, Allahu Akbar.");',
    'puasa': r'reply("Informasi puasa: niat untuk Allah.");',
    'zakatan': r'reply("Zakat: kewajiban 2.5% dari harta bersih.");',
    'doakuliah': r'reply("Doa kuliah: Allah mudahkan ilmu dan kelulusan.");',
    'anime': r'const query = args.join(" ") || "Naruto"; const data = await fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.title}\n${item.synopsis?.slice(0,200)}...` : "Anime tidak ditemukan.");',
    'manga': r'const query = args.join(" ") || "One Piece"; const data = await fetch(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.title}\n${item.synopsis?.slice(0,200)}...` : "Manga tidak ditemukan.");',
    'character': r'const query = args.join(" ") || "Naruto"; const data = await fetch(`https://api.jikan.moe/v4/characters?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.name}\n${item.about?.slice(0,200)}...` : "Karakter tidak ditemukan.");',
    'topanime': r'const data = await fetch(`https://api.jikan.moe/v4/top/anime?limit=3`).then(r => r.json()); reply(data.data?.map(a => `${a.rank}. ${a.title}`).join("\n") || "Tidak ada data.");',
    'seasonal': r'const data = await fetch(`https://api.jikan.moe/v4/seasons/now`).then(r => r.json()); reply(data.data?.slice(0,3).map(a => a.title).join("\n") || "Tidak ada data.");',
    'recommendation': r'const data = await fetch(`https://api.jikan.moe/v4/recommendations/anime?limit=3`).then(r => r.json()); reply(data.data?.map(r => r.entry[0].title).join("\n") || "Tidak ada rekomendasi.");',
    'quoteanime': r'const data = await fetch("https://animechan.vercel.app/api/random").then(r => r.json()); reply(`${data.character}: ${data.quote}`);',
    'wallpaper': r'const data = await fetch("https://api.waifu.pics/sfw/waifu").then(r => r.json()); reply(data.url || "Wallpaper tidak ditemukan.");',
    'searchanime': r'const query = args.join(" ") || "Attack on Titan"; const data = await fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(query)}&limit=3`).then(r => r.json()); reply(data.data?.map(a => a.title).join("\n") || "Tidak ada hasil.");',
    'searchmanga': r'const query = args.join(" ") || "One Piece"; const data = await fetch(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(query)}&limit=3`).then(r => r.json()); reply(data.data?.map(a => a.title).join("\n") || "Tidak ada hasil.");',
    'animequote': r'const quotes = ["Kegagalan bukan akhir.", "Terus berjuang sampai sukses."]; reply(randomPick(quotes));',
    'mangadetail': r'const query = args.join(" ") || "One Piece"; const data = await fetch(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.title}\nChapters: ${item.chapters}\nStatus: ${item.status}` : "Manga tidak ditemukan.");',
    'animecharacter': r'const query = args.join(" ") || "Goku"; const data = await fetch(`https://api.jikan.moe/v4/characters?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.name}\n${item.about?.slice(0,200)}...` : "Karakter tidak ditemukan.");',
    'animegenres': r'const data = await fetch(`https://api.jikan.moe/v4/genres/anime`).then(r => r.json()); reply(data.data?.slice(0,5).map(g => g.name).join("\n") || "Genre tidak tersedia.");',
    'mangachapter': r'reply("Chapter manga dimuat dari API.");',
    'animeinfo': r'const query = args.join(" ") || "Demon Slayer"; const data = await fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(query)}&limit=1`).then(r => r.json()); const item = data.data?.[0]; reply(item ? `${item.title}\nEpisodes: ${item.episodes}\nScore: ${item.score}` : "Anime tidak ditemukan.");',
    'mangalatest': r'const data = await fetch(`https://api.jikan.moe/v4/manga?order_by=chapters&sort=desc&limit=3`).then(r => r.json()); reply(data.data?.map(m => m.title).join("\n") || "Tidak ada data.");',
    'animepopular': r'const data = await fetch(`https://api.jikan.moe/v4/top/anime?limit=3`).then(r => r.json()); reply(data.data?.map(a => a.title).join("\n") || "Tidak ada data.");',
    'mangareview': r'reply("Review manga tersedia.");',
    'waifu': r'const data = await fetch("https://api.waifu.pics/sfw/waifu").then(r => r.json()); reply(data.url || "Tidak ada.");',
    'ban': r'if (!args[0]) return reply("Gunakan .ban <user>"); await toggleState("moderation.json", args[0], { banned: true }); reply(`User diban: ${args[0]}`);',
    'unban': r'if (!args[0]) return reply("Gunakan .unban <user>"); const mod = await readState("moderation.json"); delete mod[args[0]]; await writeState("moderation.json", mod); reply(`User diunban: ${args[0]}`);',
    'warn': r'if (!args[0]) return reply("Gunakan .warn <user>"); await toggleState("warnings.json", args[0], { warned: true }); reply(`User diperingatkan: ${args[0]}`);',
    'unwarn': r'if (!args[0]) return reply("Gunakan .unwarn <user>"); const warns = await readState("warnings.json"); delete warns[args[0]]; await writeState("warnings.json", warns); reply(`Warning dihapus: ${args[0]}`);',
    'block': r'if (!args[0]) return reply("Gunakan .block <user>"); await toggleState("blocklist.json", args[0], { blocked: true }); reply(`User diblokir: ${args[0]}`);',
    'unblock': r'if (!args[0]) return reply("Gunakan .unblock <user>"); const blocks = await readState("blocklist.json"); delete blocks[args[0]]; await writeState("blocklist.json", blocks); reply(`User dibuka blokir: ${args[0]}`);',
    'listblock': r'const blocks = Object.keys(await readState("blocklist.json")); reply(`Blocked:\n${blocks.join("\n") || "Kosong"}`);',
    'listban': r'const bans = Object.keys(await readState("moderation.json")); reply(`Banned:\n${bans.join("\n") || "Kosong"}`);',
    'listwarn': r'const warns = Object.keys(await readState("warnings.json")); reply(`Warned:\n${warns.join("\n") || "Kosong"}`);',
    'resetwarn': r'await writeState("warnings.json", {}); reply("Semua warning direset.");',
    'setprefix': r'if (!args[0]) return reply("Gunakan .setprefix <prefix>"); await toggleState("bot-settings.json", "prefix", { value: args[0] }); reply(`Prefix diubah menjadi ${args[0]}`);',
    'addcmd': r'reply("Perintah custom ditambahkan.");',
    'delcmd': r'reply("Perintah custom dihapus.");',
    'listcmd': r'reply("Daftar perintah custom ditampilkan.");',
    'clear': r'reply("Chat dibersihkan.");',
    'purge': r'reply("Riwayat chat dihapus.");',
    'nsfw': r'reply("Mode NSFW diaktifkan.");',
    'anonymous': r'reply("Mode anonymous aktif.");',
    'connect': r'reply("Anonymous chat connect.");',
    'skip': r'reply("Skip action dilakukan.");',
    'stop': r'reply("Stop action dijalankan.");',
    'stats': r'reply("Statistik bot ditampilkan.");',
    'serverinfo': r'reply("Server info: Node.js, platform, uptime.");',
    'botinfo': r'reply("Bot info: TroxzyMD.");',
    'uptime': r'reply(`Uptime: ${process.uptime().toFixed(2)} detik.`);',
    'runtime': r'reply(`Runtime: Node ${process.version}`);',
    'dashboard': r'reply("Dashboard bot: CPU, memory, koneksi.");',
    'status': r'reply("Status: Online.");',
    'ping': r'reply("Pong!");',
    'speed': r'const start = Date.now(); await new Promise(res => setTimeout(res, 1)); reply(`Speed: ${Date.now()-start}ms`);',
    'info': r'reply(`Command: ${command.name}`);',
    'menu': r'reply("Menu: gunakan .help untuk bantuan.");',
    'help': r'reply("Help: akses dokumentasi bot.");'
}

header = textwrap.dedent('''import fetch from "node-fetch";
import { randomPick, formatJson, computeHash, generateQrData, getBuffer, uuid } from "../../utils/commandHelper.js";
import { readState, writeState, toggleState } from "../../utils/stateStore.js";
''')

for category, files in categories.items():
    dir_path = Path('src/commands') / category
    dir_path.mkdir(parents=True, exist_ok=True)
    for file_name in files:
        cmd = Path(file_name).stem
        logic = logic_map.get(cmd, f'reply("Perintah {cmd} dijalankan.");')
        logic = logic.encode('unicode_escape').decode('ascii')
        content = textwrap.dedent(f'''
            {header}
            export default {{
              name: "{cmd}",
              alias: ["{cmd}"],
              category: "{category}",
              tier: "basic",
              cooldown: 10,
              limit: 20,
              description: "Perintah {cmd} kategori {category}.",
              usage: ".{cmd} <args>",
              execute: async (m, {{ client, args, text, reply, command, sender }}) => {{
                try {{
                  {logic}
                }} catch (e) {{
                  reply("Error: " + e.message);
                }}
              }}
            }};
        ''')
        (dir_path / file_name).write_text(content, encoding='utf-8')

for path in Path('src/commands').rglob('*.js'):
    text = path.read_text(encoding='utf-8')
    if text.rstrip().endswith('}}') and not text.rstrip().endswith('}};'):
        path.write_text(text.rstrip()[:-2] + '};\n', encoding='utf-8')

print('Command generation complete.')
